services:
  db:
    image: postgres
    restart: always
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local
    ports:
      - '5432:5432'
